### ISSUE TITLE
Can i configure exponential usage in result?

### ISSUE THREAD

**Issue by junhanRyu** [Keelar/ExprK#8]
first of all, Thank you for your code!

my question is that how can i configure exponential result?
for example, the result is 10.01+E3 for 10000+10. I want to use exponential only for much larger numbers.

Thank you again.

**Comment by Keelar** [comment]
`eval()` returns a `BigDecimal` which is part of the Java standard library. Calling `toString()` on a `BigDecimal` will use scientific notation. If you want the number without scientific notation you can use `toPlainString()`. Then just use an `if` statement to decide which one to use based on the size of the number.
